name: MoonLakeGUI
main: com.minecraft.moonlake.gui.GUIPlugin
version: 1.5
author: Month_Light
website: http://www.mcyszh.com

# depend: MoonLake 1.7 for override: https://github.com/u2g/MoonLake/tree/override
depend: [MoonLake]